from pathlib import Path

path = Path(r'C:\Users\kalin\Downloads\AssetRipper_win_x64\okice\okice\Assets\MonoBehaviour\AFTERLIVES Dialogue Database.asset')
text = path.read_text(encoding='utf-8')

replacements = [
    ('Zaključano je.', 'Zaključano.'),
    ('Odlazak.', 'Idem.'),
    ('ODLAZAK', 'IDEM'),
    ('Telefon zvoni.\n\nIznenađujuće - Maddie.', 'Telefon zvoni.\n\nMaddie.'),
    ('PODIGNI', 'PRIMI'),
    ('"Što se, dovraga, zbiva?"', '"Što se, dovraga, događa?"'),
    ('Ne znam', 'Ne znam.'),
    ('Jesi li dobro?', 'Jesi li dobro?'),
    ('"Da. Jesam. Molim te, ne brini za mene."', '"Da. Jesam. Nemoj se brinuti za mene."'),
    ('Jesi li ozlijeđena?', 'Jesi li ranjena?'),
    ('Doći ću', 'Doći ću.'),
    ('"Mislim da nisam. Mislim, ne osjećam bol."', '"Mislim da nisam. Ne osjećam bol."'),
    ('"Ne! Molim te, nemoj.\n\nStvarno sam dobro. Htjela sam samo pitati znaš li što se zbiva."', '"Ne! Molim te, nemoj.\n\nStvarno sam dobro. Samo sam te htjela pitati što se događa."'),
    ('Jesi li sigurna?', 'Jesi li sigurna?'),
    ('Zaista bih trebao doći', 'Trebao bih doći.'),
    ('"Da. Ne brini."', '"Da. Nemoj se brinuti."'),
    ('"...dobro. Ali sumnjam da je most prema Bloku 29 još otvoren."', '"...dobro. Ali sumnjam da je most prema Bloku 29 još uvijek otvoren."'),
    ('Pokušat ću (ODLAZAK)', 'Pokušat ću. (IDEM)'),
    ('"Uši mi još zvone od udara one bombe."', '"Još mi zvrje u ušima od one bombe."'),
    ('Slika kina koje je Maddie nekoć posjećivala.\n\nMaddie obožava filmove.', 'Slika kina koje je Maddie nekoć posjećivala.\n\nMaddie je voljela filmove.'),
    ('To je kratka bilješka koju je napisao tvoj susjed.', 'To je kratka bilješka tvog susjeda.'),
    ('"Za Maddie:\n\nZaštitit ću te."', '"Za Maddie:\n\nZaštitit ću te."'),
    ('To je neoprani tanjur. Tvoj je susjed otišao u žurbi.', 'To je neoprani tanjur. Tvoj susjed otišao je u žurbi.'),
    ('Nakon kratkog zujanja začuješ nadzorničin stari glas. \n\n"Ima li koga?" pita.', 'Nakon kratkog zujanja čuješ nadzorničin stari glas.\n\n"Ima li koga?" pita.'),
    ('Ja sam tvoj susjed', 'Ja sam tvoj susjed.'),
    ('Treba mi pristup mostu', 'Treba mi pristup mostu.'),
    ('Duboko udahne.\n\n"Zašto još nisi otišao, dragi? Rekli su nam da se evakuiramo. Čovjek s jednim okom već je otišao."', 'Duboko udahne.\n\n"Zašto još nisi otišao, dragi? Rekli su nam da se evakuiramo. Čovjek s jednim okom već je otišao."'),
    ('Moram pronaći Maddie', 'Moram pronaći Maddie.'),
    ('"Maddie? \n\nOh, Maddie. Moj unuk neprestano priča o njoj. \n\nMoj unuk! Ni on se ne želi evakuirati, budala jedna."', '"Maddie?\n\nMaddie. Moj unuk neprestano priča o njoj.\n\nMoj unuk! Ni on se ne želi evakuirati. Bez razuma je."'),
    ('"Most? Ne možeš, dragi. Žao mi je. Vojnici su mi naredili da ga zaključam.\n\nA zašto bi uopće išao na most?" \n\n', '"Most? Ne možeš, dragi. Žao mi je. Vojnici su mi naredili da ga zaključam.\n\nA zašto bi uopće išao na most?"'),
    ('Zaista mi treba pristup mostu', 'Zaista mi treba pristup mostu.'),
    ('"Ne znam!" vikne nadzornica, naizgled glasnije nego što je namjeravala. \n\n"Zaključao se u svom stanu. Nemam pojma što ondje radi."', '"Ne znam!" vikne nadzornica, glasnije nego što je namjeravala.\n\n"Zaključao se u stanu. Ne znam što ondje radi."'),
    ('"Znam, dragi. Ali vojnici ti neće dopustiti. Vjerojatno bi me ubili kad bih ti dopustila da prijeđeš most."', '"Znam, dragi. Ali vojnici ti to neće dopustiti. Vjerojatno bi me ubili kad bih ti dopustila da prijeđeš most."'),
    ('Nadzornica oklijeva.\n\n"...stvarno? Ako to učiniš, mislim da bih mogla otvoriti most, samo za tebe. Vojnici možda neće ni primijetiti.\n\nAli moraš nagovoriti mog unuka da ode."', 'Nadzornica oklijeva.\n\n"...stvarno? Ako to učiniš, mislim da bih mogla otvoriti most. Samo za tebe. Vojnici možda ni ne bi primijetili.\n\nAli moraš nagovoriti mog unuka da ode."'),
    ('Zauzvrat bih mogao izvući tvog unuka', 'Zauzvrat bih mogao izvući tvog unuka.'),
    ('Hoću', 'Hoću.'),
    ('"Puno ti hvala. Od srca to mislim. Otključat ću vrata njegova stana. \n\nI molim te, budi oprezan."', '"Hvala ti. To mislim od srca. Otključat ću vrata njegova stana.\n\nI molim te, budi oprezan."'),
    ('"Ponekad nemam pojma što mu se sve mota po glavi."', '"Ponekad ne znam što mu se sve vrti po glavi."'),
    ('\n\nNadzornica isključuje interfon. \n"I ne mogu ništa učiniti u vezi toga," kaže.', '\n\nNadzornica isključuje interfon.\n"Ne mogu ništa učiniti u vezi toga", kaže.'),
    ('Što govori o Maddie?', 'Što kažeš o Maddie?'),
    ('"Ma, ovo i ono."', '"Ma, ovo i ono."'),
    ('"To bi te samo odvelo dublje u zgradu. Rekli su nam da se evakuiramo. Čovjek s jednim okom već je otišao."', '"To bi te samo odvelo dublje u zgradu. Rekli su nam da se evakuiramo. Čovjek s jednim okom već je otišao."'),
    ('To je razbijeno zrcalo.', 'To je razbijeno zrcalo.'),
    ('Zrcalo je sada cijelo.\n\nPrimjećuješ nekakav natpis urezan pri dnu.', 'Zrcalo je sada cijelo.\n\nPrimjećuješ natpis urezan pri dnu.'),
    ('"Ispravio sam sve svoje nesavršenosti.\n\nSad će me voljeti."', '"Ispravio sam sve svoje nedostatke.\n\nSad će me voljeti."'),
    ('"Maddie će me sada voljeti."', '"Maddie će me sada voljeti."'),
    ('Tekst na ekranu glasi: "Pristup mostu Bloka 29".\n\nNe znaš šifru.', 'Tekst na ekranu glasi: "Pristup mostu Bloka 29".\n\nNe znaš šifru.'),
    ('Bilješka je pribijena na prašnjavo zrcalo.', 'Bilješka je pribijena uz prašnjavo zrcalo.'),
    ('"Na desnoj strani vrata imam ružnu mrlju.\n\nOči mi izgledaju grozno.\n\nMislim da nešto nije u redu s mojom kožom."', '"Na desnoj strani vrata imam ružnu mrlju.\n\nOči mi izgledaju grozno.\n\nMislim da nešto nije u redu s mojom kožom."'),
    ('"Ovaj je odvijač bio dovoljno oštar.\n\nRužne mrlje više nema."', '"Ovaj je odvijač bio dovoljno oštar.\n\nRužne mrlje više nema."'),
    ('"Popravljeno:\n\n- Zubi\n- Obrve\n- Nokti\n- Koža"', '"Popravljeno:\n\n- Zubi\n- Obrve\n- Nokti\n- Koža"'),
    ('"Za popraviti:\n\n- Oči\n\nOči mi izgledaju grozno."', '"Za popraviti:\n\n- Oči\n\nOči mi izgledaju grozno."'),
    ('Niz cijevi koje vode do kupaonice u prizemlju. \n\nNešto bi se moglo pričvrstiti na držač po sredini.', 'Niz cijevi koje vode do kupaonice u prizemlju.\n\nNa sredini bi se mogao pričvrstiti neki držač.'),
    ('To je ljudska koža.', 'To je ljudska koža.'),
    ('To je mali lokot sa simbolom oka.', 'To je mali lokot sa simbolom oka.'),
    ('To je KLJUČ OKA (3 UPORABE).', 'To je KLJUČ OKA (3 uporabe).'),
    ('To je bilješka.', 'To je bilješka.'),
    ('"Hodnici su prazni.\n\nZaglavio sam ovdje, okružen svim ovim zrcalima."', '"Hodnici su prazni.\n\nZaglavio sam ovdje, okružen ovim zrcalima."'),
    ('"Od sada ću gledati samo one slomljene."', '"Od sada ću gledati samo slomljene."'),
    ('Bilješka je pribijena za stražnju stranu ormara.', 'Bilješka je pribijena na stražnju stranu ormara.'),
    ('"Pokušat ću opet sutra.\n\nIzgubio sam pilu."', '"Pokušat ću opet sutra.\n\nIzgubio sam pilu."'),
    ('"Svim stanarima Bloka 28,\n\nOvo je izvanredno stanje. \n\nSmjesta evakuirajte grad."', '"Svim stanarima Bloka 28,\n\nOvo je hitno.\n\nSmjesta evakuirajte grad."'),
    ('"Znam šifru za most.\n\nPomozimo jedno drugome."', '"Znam šifru za most.\n\nPomozimo jedno drugome."'),
    ('"Molim te, pomozi mi popraviti moje posebno zrcalo.\n\nOd udara je palo sa stola i razbilo se.\n\nNe znam što ću bez njega."', '"Molim te, pomozi mi popraviti moje posebno zrcalo.\n\nOd udara je palo sa stola i razbilo se.\n\nNe znam što ću bez njega."'),
    ('"Mojih groznih očiju više nema.\n\nBol će se isplatiti."', '"Mojih groznih očiju više nema.\n\nBol će se isplatiti."'),
    ('To je PAR LJUDSKIH OČIJU.', 'To je PAR LJUDSKIH OČIJU.'),
    ('To je niz ležišta s dva ljudska oka na vrhu.', 'To je niz ležišta s dva ljudska oka na vrhu.'),
    ('To je KRHOTINA ZRCALA (3/3).', 'To je KRHOTINA ZRCALA (3/3).'),
    ('"Kako sam obećala:\n\nŠifra za most glasi \n2-2-0-0-0."', '"Kako sam obećala:\n\nŠifra za most glasi:\n2-2-0-0-0."'),
    ('To je mala knjiga pjesama koje si napisao o Maddie. \nNaslov glasi: "Moja toplina u Hladnom gradu".\n\nNikad joj nisi pokazao nijednu svoju pjesmu, ali kad ih zapišeš, postaju tako divno stvarne.', 'To je mala knjiga pjesama koje si napisao o Maddie.\nNaslov glasi: "Moja toplina u Hladnom gradu".\n\nNikad joj nisi pokazao nijednu pjesmu, a kad ih zapišeš, postaju tako stvarne.'),
    ('Telefon zvoni. To je Maddie.', 'Telefon zvoni. To je Maddie.'),
    ('"Ponavljam, ne moraš dolaziti.\n\nStvarno sam dobro."', '"Ponavljam, ne moraš dolaziti.\n\nStvarno sam dobro."'),
    ('Svejedno ću doći', 'Svejedno ću doći.'),
    ('"Misli na vlastitu sigurnost, molim te."', '"Misli na vlastitu sigurnost, molim te."'),
    ('Ne brini', 'Ne brini.'),
    ('Tvoja je sigurnost važnija', 'Tvoja je sigurnost važnija.'),
    ('"Dobro... ako baš inzistiraš.\n\nAli molim te, nemoj ovo shvatiti krivo."', '"Dobro... ako baš inzistiraš.\n\nAli molim te, nemoj ovo shvatiti krivo."'),
    ('Uskoro stižem', 'Uskoro stižem.'),
    ('Čuvaj se', 'Čuvaj se.'),
    ('"Dobro."', '"Dobro."'),
    ('Volim te', 'Volim te.'),
    ('Maddie je već spustila slušalicu.\n\nNije te čula.', 'Maddie je već spustila slušalicu.\n\nNije te čula.'),
    ('"Već sam na sigurnom, mislim."', '"Već sam na sigurnom. Mislim."'),
    ('Molim te, pusti me da dođem', 'Molim te, pusti me da dođem.'),
    ('Zvučiš nesigurno', 'Zvučiš nesigurno.'),
    ('"Pa... jednostavno ne znam što bih rekla."', '"Pa... jednostavno ne znam što bih rekla."'),
    ('"...dobro.\n\nNemoj ovo shvatiti krivo."', '"...dobro.\n\nNemoj ovo shvatiti krivo."'),
    ('Neću', 'Neću.'),
    ('U redu je', 'U redu je.'),
    ('"...možeš doći.\n\nAli molim te, nemoj ovo shvatiti krivo."', '"...možeš doći.\n\nAli molim te, nemoj ovo shvatiti krivo."'),
    ('"U redu."', '"U redu."'),
    ('"..."', '"..."'),
    ('Gdje je Blok 29?', 'Gdje je Blok 29?'),
    ('"...toliko dugo... a što zauzvrat dobivam?..."', '"...toliko dugo... a što zauzvrat dobivam?..."'),
    ('Trebaš li pomoć?', 'Trebaš li pomoć?'),
    ('"...stotine... ne, tisuće... mrtvih..."', '"...stotine... ne, tisuće... mrtvih..."'),
    ('"...gdje je moja nagrada?..."', '"...gdje je moja nagrada?..."'),
    ('"...boli..."', '"...boli..."'),
    ('"...u bunkeru s tvoje lijeve strane ima tableta. \n\n...donesi mi ih i prebacit ću te do Bloka 29...."', '"...u bunkeru s tvoje lijeve strane ima tableta.\n\n...donesi mi ih i prebacit ću te do Bloka 29...."'),
    ('Moram doći do Bloka 29', 'Moram doći do Bloka 29.'),
    ('Pilot ti daje KLJUČ BUNKERA.', 'Pilot ti daje KLJUČ BUNKERA.'),
    ('"...mislila sam da hoće..."', '"...mislila sam da hoće..."'),
    ('Vrata su zabijena daskama.\n\nKljučanica je neobično velika.', 'Vrata su zabijena daskama.\n\nKljučanica je neobično velika.'),
    ('Na stolu je bočica tableta.', 'Na stolu je bočica tableta.'),
    ('"Trebam joj."', '"Trebam je."'),
    ('"Za nju bih učinio sve."', '"Za nju bih učinio sve."'),
    ('"Zapravo, nemoj dolaziti.\n\nMolim te, nemoj."', '"Zapravo, nemoj dolaziti.\n\nMolim te, nemoj."'),
    ('Zašto ne?', 'Zašto ne?'),
    ('Kako to misliš?', 'Kako to misliš?'),
    ('"Nazvala sam samo zbog te bombe.\n\nNemoj ovo shvatiti pogrešno."', '"Nazvala sam samo zbog te bombe.\n\nNemoj ovo shvatiti pogrešno."'),
    ('"Samo sam se zabrinula za tebe. \n\nNisam te trebala zvati. Možda je sve to moja krivnja."', '"Samo sam se zabrinula za tebe.\n\nNisam te trebala zvati. Možda je sve to moja krivnja."'),
    ('Nije tvoja krivnja', 'Nije tvoja krivnja.'),
    ('Jesi li na sigurnom?', 'Jesi li na sigurnom?'),
    ('Moram te vidjeti', 'Moram te vidjeti.'),
    ('"Nije važno.\n\nMolim te, idi. Ostavi me na miru."', '"Nije važno.\n\nMolim te, idi. Ostavi me na miru."'),
    ('"Da, na sigurnom sam.\n\nMolim te, idi. Ostavi me na miru."', '"Da, na sigurnom sam.\n\nMolim te, idi. Ostavi me na miru."'),
    ('"Ostavi me na miru. Molim te, samo idi."', '"Ostavi me na miru. Molim te, samo idi."'),
    ('Maddie?', 'Maddie?'),
    ('Spustila je slušalicu.\n\nTrebao bi otići k njoj.', 'Spustila je slušalicu.\n\nTrebao bi otići k njoj.'),
    ('SAČMARICA.\n\nNe znaš se njome služiti. \nNisi poput pilota.', 'SAČMARICA.\n\nNe znaš se njome služiti.\nNisi poput pilota.'),
    ('To je PILA.', 'To je PILA.'),
    ('To je nekakav nadzorni sustav.', 'To je neki nadzorni sustav.'),
    ('Monitori prikazuju čitav Maddien stan, naizgled snimljen pomoću nekoliko skrivenih kamera.', 'Monitori prikazuju čitav Maddien stan, snimljen nekoliko skrivenih kamera.'),
    ('PROVJERI DNEVNI BORAVAK', 'PROVJERI DNEVNI BORAVAK'),
    ('PROVJERI KUHINJU', 'PROVJERI KUHINJU'),
    ('PROVJERI SPAVAĆU SOBU', 'PROVJERI SPAVAĆU SOBU'),
    ('Njezin je dnevni boravak zapušten i sve djeluje krhko.\n\nNa stolu leži kutija cigareta.', 'Njezin je dnevni boravak zapušten. Sve djeluje krhko.\n\nNa stolu leži kutija cigareta.'),
    ('Kuhinja je neugledna.\n\nNekoliko neopranih tanjura naslagano je na pultu.', 'Kuhinja je neugledna.\n\nNa pultu je naslagano nekoliko neopranih tanjura.'),
    ('Vidiš Maddie kako leži na kauču i gleda televiziju.\n\nKao i uvijek, savršena je.', 'Vidiš Maddie kako leži na kauču i gleda televiziju.\n\nKao i uvijek, savršena je.'),
    ('"Štitim je, pa je posve pošteno da znam što smjera.\n\nValjda godi biti s nekim tako blizak."', '"Štitim je, pa je posve pošteno da znam što smjera.\n\nValjda godi biti s nekim tako bliskim."'),
    ('"Kad su mi naredili da branim Blok 29, mislio sam da sanjam, tako sam bio sretan. \n\nNitko neće stati između nas. Sa mnom je sigurna."', '"Kad su mi naredili da branim Blok 29, mislio sam da sanjam. Tako sam bio sretan.\n\nNitko neće stati između nas. Sa mnom je sigurna."'),
    ('To je bočica tableta.\n\nTrebao bi je odnijeti pilotu.', 'To je bočica tableta.\n\nTrebao bi je odnijeti pilotu.'),
    ('Ne bi smio izaći iz bunkera prije nego uzmeš pilotove tablete.', 'Ne smiješ izaći iz bunkera dok ne uzmeš pilotove tablete.'),
    ('DAJ TABLETE', 'DAJ TABLETE'),
    ('Pilot uzima tablete.', 'Pilot uzima tablete.'),
    ('"...hvala ti..."', '"...hvala ti..."'),
    ('Odvedi me do Bloka 29', 'Odvedi me do Bloka 29.'),
    ('"...žao mi je, ne mogu.\n\nNemam ključ. Nemam baš ništa."', '"...žao mi je, ne mogu.\n\nNemam ključ. Nemam baš ništa."'),
    ('"Uostalom, ne bih ti ni dopustila. Tko zna što bi učinio..."', '"Uostalom, ne bih ti ni dopustila. Tko zna što bi učinio..."'),
    ('O čemu govoriš?', 'O čemu govoriš?'),
    ('"Žao mi je...\n\nNe zaslužujem ništa od ovoga..."', '"Žao mi je...\n\nNe zaslužujem ništa od ovoga..."'),
    ('Lagala si mi', 'Lagala si mi.'),
    ('"...kloni se Maddie..."', '"...kloni se od Maddie..."'),
    ('"...izgubio sam nogu za tu djevojku."', '"...izgubio sam nogu zbog te djevojke."'),
    ('Pilot više ne odgovara.\n\nNe trebaš ga.', 'Pilot više ne odgovara.\n\nNe trebaš ga.'),
    ('"Što si to izgubio?"', '"Što si to izgubio?"'),
    ('"Blok 29 - Dizala"', '"Blok 29 - Dizala"'),
    ('NAZOVI MADDIE', 'NAZOVI MADDIE'),
    ('"Kloni se."', '"Kloni se."'),
    ('Zašto?', 'Zašto?'),
    ('Ne mogu', 'Ne mogu.'),
    ('"Nazvala sam te jer je pala bomba. U ratu smo. \n\nHtjela sam znati jesi li dobro. Samo zbog toga sam nazvala."', '"Nazvala sam te jer je pala bomba. U ratu smo.\n\nHtjela sam znati jesi li dobro. Samo zbog toga sam nazvala."'),
    ('"Zašto misliš da to išta znači?\n\nUvijek misliš da baš sve \nnešto znači."', '"Zašto misliš da to išta znači?\n\nUvijek misliš da sve nešto znači."'),
    ('"Ni ne poznajem te."', '"Ni ne poznajem te."'),
    ('"Plašiš me. Kloni se."', '"Plašiš me. Kloni se."'),
    ('Trebam te', 'Trebam te.'),
    ('Dolazim', 'Dolazim.'),
    ('"Nisam htjela da ovako ispadne. \n\nNisam te trebala zvati."', '"Nisam htjela da ovako ispadne.\n\nNisam te trebala zvati."'),
    ('Maddie je spustila slušalicu.\n\nDošao si tako daleko. Ne možeš sada stati.', 'Maddie je spustila slušalicu.\n\nDošao si tako daleko. Ne možeš se sada zaustaviti.'),
    ('Najprije bi trebao nazvati Maddie.', 'Najprije bi trebao nazvati Maddie.'),
    ('Maddie je odškrinula vrata.\n\nNe vidiš je, ali znaš da je unutra.', 'Maddie je odškrinula vrata.\n\nNe vidiš je, ali znaš da je unutra.'),
    ('Ovdje sam', 'Ovdje sam.'),
    ('"Gubi se iz mog stana. Molim te, samo me ostavi na miru."', '"Gubi se iz mog stana. Molim te, ostavi me na miru."'),
    ('"Što želiš od mene? \n\nŠto, dovraga, želiš?"', '"Što želiš od mene?\n\nŠto, dovraga, želiš?"'),
    ('Zaštitit ću te', 'Zaštitit ću te.'),
    ('"Da me zaštitiš? Od čega?\n\nVeć sam sigurna, zahvaljujući onom pilotu." ', '"Da me zaštitiš? Od čega?\n\nVeć sam sigurna, zahvaljujući onom pilotu."'),
    ('"Izgubio je nogu kako bih ja bila sigurna.\n\nZar to nije hrabro?"', '"Izgubio je nogu kako bih ja bila sigurna.\n\nZar to nije hrabro?"'),
    ('"...o čemu ja uopće govorim?\n\nOstavi me na miru. Samo idi."', '"...o čemu ja uopće govorim?\n\nOstavi me na miru. Samo idi."'),
    ('"...izgubio je nogu zbog mene..."', '"...izgubio je nogu zbog mene..."'),
    ('"...izgubio je nogu zbog mene...\n\n...tako hrabar..."', '"...izgubio je nogu zbog mene...\n\n...tako hrabar..."'),
    ('Primjećuješ PILU koju si uzeo iz bunkera.\n\nI ti bi mogao biti hrabar.', 'Primjećuješ PILU koju si uzeo iz bunkera.\n\nI ti bi mogao biti hrabar.'),
    ('Mogao bi biti tako hrabar.\n\nTako hrabar.\n\nMaddie će te voljeti zbog ovoga.', 'Mogao bi biti tako hrabar.\n\nTako hrabar.\n\nMaddie će te zbog toga voljeti.'),
    ('PREPILI NOGU', 'PREPILI NOGU'),
    ('Ne možeš sada stati.\n\nMaddie će te voljeti budeš li hrabar.', 'Ne možeš se sada zaustaviti.\n\nMaddie će te voljeti, ako budeš hrabar.'),
    ('"Što si to učinio sebi?\n\nŠto nije u redu s tobom?"', '"Što si to učinio sebi?\n\nŠto nije u redu s tobom?"'),
    ('Hrabar sam', 'Hrabar sam.'),
    ('Za tebe bih učinio sve', 'Za tebe bih učinio sve.'),
    ('"Nosi se dovraga od mene.\n\nGubi se iz mog stana."', '"Nosi se dovraga od mene.\n\nGubi se iz mog stana."'),
    ('Maddie tiho plače.', 'Maddie tiho plače.'),
    ('"O, Bože..."', '"O, Bože..."'),
    ('"Molim te, idi..."', '"Molim te, idi..."'),
    ('Bit ću savršen', 'Bit ću savršen.'),
    ('"...o čemu ti to, dovraga, govoriš?"', '"...o čemu ti to, dovraga, govoriš?"'),
    ('DRŽI ODVIJAČE', 'DRŽI ODVIJAČE'),
    ('Odvijači izgledaju dovoljno oštro. \n\nBit ćeš savršen.', 'Odvijači izgledaju dovoljno oštro.\n\nBit ćeš savršen.'),
    ('PROBODI DESNO OKO', 'PROBODI DESNO OKO'),
    ('PROBODI LIJEVO OKO', 'PROBODI LIJEVO OKO'),
    ('Boli.\n\nMaddie će te voljeti.', 'Boli.\n\nMaddie će te voljeti.'),
    ('"Molim te, prestani, \npreklinjem te.', '"Molim te, prestani,\npreklinjem te.'),
    ('"Molim te, prestani, \npreklinjem te."', '"Molim te, prestani,\npreklinjem te."'),
    ('"O Bože, molim te, prestani."', '"O Bože, molim te, prestani."'),
    ('"Učinit ću što god želiš, \nsamo prestani, molim te prestani."', '"Učinit ću što god želiš,\nsamo prestani, molim te prestani."'),
    ('"...volim te!\n\nToliko te volim..."', '"...volim te!\n\nToliko te volim..."'),
    ('U ormariću je bilješka.', 'U ormariću je bilješka.'),
    ('"Sve je slomljeno, propušta i dotrajalo.\n\nRekli su da će poslati nekoga da to popravi, ali nikad nisu."', '"Sve je slomljeno, propušta i dotrajalo.\n\nRekli su da će poslati nekoga da to popravi, ali nikad nisu."'),
    ('To je maketa borbenog aviona.', 'To je maketa borbenog aviona.'),
    ('To je prazan umivaonik.', 'To je prazan umivaonik.'),
    ('To je kutija Maddienih cigareta.', 'To je kutija Maddienih cigareta.'),
    ('Vrata Maddiene spavaće sobe.\n\nZaključana su.', 'Vrata Maddiene spavaće sobe.\n\nZaključana su.'),
    ('Veliko zrcalo. \n\nPred njim leži par odvijača.', 'Veliko zrcalo.\n\nPred njim leži par odvijača.'),
    ('POGLEDAJ U ZRCALO', 'POGLEDAJ U ZRCALO'),
    ('Ali te nesavršenosti možeš ispraviti.\n\nMožeš biti besprijekoran i Maddie će te voljeti.\n\nSamo joj to moraš pokazati.', 'Ali te nedostatke možeš ispraviti.\n\nMožeš biti besprijekoran i Maddie će te voljeti.\n\nSamo joj to moraš pokazati.'),
    ('Oči ti izgledaju grozno.', 'Oči ti izgledaju grozno.'),
    ('UZMI ODVIJAČE', 'UZMI ODVIJAČE'),
    ('Vidiš vlastito lice.\n\nIzgledaš umorno, no nježno i odlučno.\n\nZašto te Maddie ne može voljeti?', 'Vidiš vlastito lice.\n\nIzgledaš umorno, ali nježno i odlučno.\n\nZašto te Maddie ne može voljeti?'),
    ('POGLEDAJ IZBLIZA', 'POGLEDAJ IZBLIZA'),
    ('...to su zacijelo tvoje oči. \n\nMutne, krvave i iznurene.', '...to su zacijelo tvoje oči.\n\nMutne, krvave i iznurene.'),
]

for old, new in replacements:
    old_escaped = old.replace('\\', '\\\\').replace('"', '\\"').replace('\n', '\\n')
    new_escaped = new.replace('\\', '\\\\').replace('"', '\\"').replace('\n', '\\n')
    if f'value: "{old_escaped}"' in text:
        text = text.replace(f'value: "{old_escaped}"', f'value: "{new_escaped}"')
    else:
        # fallback for values without the exact quoted form
        text = text.replace(old, new)

path.write_text(text, encoding='utf-8')
print('Rewrote dialogue text values.')
